### ISSUE TITLE
ice是怎么部署的

### ISSUE THREAD

**Issue by roy2651** [galaxy-s10/billd-desk#1]
你好，一个很棒的项目，我想问一下，你的ice是基于coturn部署嘛，还有ssr在里面的作用是推流嘛，在投屏的场景可以使用ssr嘛，

**Comment by galaxy-s10** [comment]
> 你好，一个很棒的项目，我想问一下，你的ice是基于coturn部署嘛，还有ssr在里面的作用是推流嘛，在投屏的场景可以使用ssr嘛，

是基于coturn部署，没有用到srs
