### ISSUE TITLE
Is it not supported by older browsers?

### ISSUE THREAD

**Issue by 91Bruce** [galaxy-s10/billd-desk#2]
Hi, I have a question and I want some answers .
I used chrome v72 to open https://live.hsslive.cn/ and https://desk.hsslive.cn/ but got errors .
Whether there are version restrictions ?

**Comment by galaxy-s10** [comment]
> Hi, I have a question and I want some answers . I used chrome v72 to open https://live.hsslive.cn/ and https://desk.hsslive.cn/ but got errors . Whether there are version restrictions ?

yes
